<?php



/**
 * This class defines the structure of the 'ref_marque' table.
 *
 *
 * This class was autogenerated by Propel 1.6.6-dev on:
 *
 * 03/21/14 17:07:49
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class RefMarqueTableMap extends TableMap
{

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.RefMarqueTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
		// attributes
		$this->setName('ref_marque');
		$this->setPhpName('RefMarque');
		$this->setClassname('RefMarque');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('MARQUE_ID', 'MarqueId', 'INTEGER', true, null, null);
		$this->addColumn('MARQUE_LIBELLE', 'MarqueLibelle', 'VARCHAR', false, 127, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
		$this->addRelation('TblVoiture', 'TblVoiture', RelationMap::ONE_TO_MANY, array('marque_id' => 'id_marque', ), null, null, 'TblVoitures');
	} // buildRelations()

	/**
	 *
	 * Gets the list of behaviors registered for this table
	 *
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // RefMarqueTableMap
