<?php



/**
 * This class defines the structure of the 'tbl_client' table.
 *
 *
 * This class was autogenerated by Propel 1.6.6-dev on:
 *
 * 03/23/14 17:30:02
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class TblClientTableMap extends TableMap
{

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.TblClientTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
		// attributes
		$this->setName('tbl_client');
		$this->setPhpName('TblClient');
		$this->setClassname('TblClient');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID_CLIENT', 'IdClient', 'INTEGER', true, null, null);
		$this->addColumn('CIN_CLIENT', 'CinClient', 'VARCHAR', false, 10, null);
		$this->addColumn('NOM_CLIENT', 'NomClient', 'VARCHAR', false, 255, null);
		$this->addColumn('PRENOM_CLIENT', 'PrenomClient', 'VARCHAR', false, 255, null);
		$this->addForeignKey('SITUATION', 'Situation', 'INTEGER', 'ref_situation', 'ID_SITUATION', false, null, null);
		$this->addColumn('AGE_CLIENT', 'AgeClient', 'INTEGER', false, null, null);
		$this->addColumn('NUM_TEL', 'NumTel', 'INTEGER', false, null, null);
		$this->addColumn('ADRESSE_CLIENT', 'AdresseClient', 'VARCHAR', false, 255, null);
		$this->addColumn('FONCTION_CLIENT', 'FonctionClient', 'VARCHAR', false, 255, null);
		$this->addColumn('IS_EMPLOYE', 'IsEmploye', 'BOOLEAN', false, 1, false);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('DELETED_AT', 'DeletedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
		$this->addRelation('RefSituation', 'RefSituation', RelationMap::MANY_TO_ONE, array('situation' => 'id_situation', ), null, null);
		$this->addRelation('TblFacture', 'TblFacture', RelationMap::ONE_TO_MANY, array('id_client' => 'id_employe', ), null, null, 'TblFactures');
		$this->addRelation('TblVoiture', 'TblVoiture', RelationMap::ONE_TO_MANY, array('id_client' => 'id_client', ), null, null, 'TblVoitures');
	} // buildRelations()

	/**
	 *
	 * Gets the list of behaviors registered for this table
	 *
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'soft_delete' => array('deleted_column' => 'deleted_at', ),
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', ),
		);
	} // getBehaviors()

} // TblClientTableMap
