<?php



/**
 * This class defines the structure of the 'tbl_depances' table.
 *
 *
 * This class was autogenerated by Propel 1.6.6-dev on:
 *
 * 11/22/13 16:57:11
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class TblDepancesTableMap extends TableMap
{

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.TblDepancesTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
		// attributes
		$this->setName('tbl_depances');
		$this->setPhpName('TblDepances');
		$this->setClassname('TblDepances');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID_DEPANCES', 'IdDepances', 'INTEGER', true, null, null);
		$this->addColumn('DATE_DEPANCES', 'DateDepances', 'DATE', false, null, null);
		$this->addForeignKey('ID_REF_DEPANCES', 'IdRefDepances', 'INTEGER', 'ref_depances', 'ID_REF_DEPANCES', false, null, null);
		$this->addColumn('MONTANT_DEPANCES', 'MontantDepances', 'DOUBLE', false, null, null);
		$this->addColumn('ETAT_PAYEMENT', 'EtatPayement', 'BOOLEAN', false, 1, false);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
		$this->addRelation('RefDepances', 'RefDepances', RelationMap::MANY_TO_ONE, array('id_ref_depances' => 'id_ref_depances', ), null, null);
	} // buildRelations()

	/**
	 *
	 * Gets the list of behaviors registered for this table
	 *
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // TblDepancesTableMap
