<?php



/**
 * This class defines the structure of the 'tbl_facture' table.
 *
 *
 * This class was autogenerated by Propel 1.6.6-dev on:
 *
 * 01/09/14 10:18:29
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class TblFactureTableMap extends TableMap
{

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.TblFactureTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
		// attributes
		$this->setName('tbl_facture');
		$this->setPhpName('TblFacture');
		$this->setClassname('TblFacture');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID_FACTURE', 'IdFacture', 'INTEGER', true, null, null);
		$this->addForeignKey('ID_VOITURE', 'IdVoiture', 'INTEGER', 'tbl_voiture', 'ID_VOITURE', false, null, null);
		$this->addColumn('ID_TYPE_LAVAGE', 'IdTypeLavage', 'INTEGER', false, null, null);
		$this->addColumn('PRIX_LAVAGE', 'PrixLavage', 'DOUBLE', false, null, null);
		$this->addColumn('COMMENTAIRE_REGLEMENT', 'CommentaireReglement', 'VARCHAR', false, 255, null);
		$this->addColumn('DATE_REGLEMENT', 'DateReglement', 'TIMESTAMP', false, null, null);
		$this->addColumn('ETAT', 'Etat', 'BOOLEAN', false, 1, false);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
		$this->addRelation('TblVoiture', 'TblVoiture', RelationMap::MANY_TO_ONE, array('id_voiture' => 'id_voiture', ), null, null);
		$this->addRelation('LnkTypeLavageFacture', 'LnkTypeLavageFacture', RelationMap::ONE_TO_MANY, array('id_facture' => 'id_facture', ), null, null, 'LnkTypeLavageFactures');
		$this->addRelation('TblTicket', 'TblTicket', RelationMap::ONE_TO_MANY, array('id_facture' => 'id_facture', ), null, null, 'TblTickets');
	} // buildRelations()

	/**
	 *
	 * Gets the list of behaviors registered for this table
	 *
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // TblFactureTableMap
