<?php



/**
 * This class defines the structure of the 'tbl_ticket' table.
 *
 *
 * This class was autogenerated by Propel 1.6.6-dev on:
 *
 * 01/09/14 10:18:29
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class TblTicketTableMap extends TableMap
{

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.TblTicketTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
		// attributes
		$this->setName('tbl_ticket');
		$this->setPhpName('TblTicket');
		$this->setClassname('TblTicket');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID_TICKET', 'IdTicket', 'INTEGER', true, null, null);
		$this->addForeignKey('ID_FACTURE', 'IdFacture', 'INTEGER', 'tbl_facture', 'ID_FACTURE', false, null, null);
		$this->addColumn('DATE_ENTREE_GARAGE', 'DateEntreeGarage', 'TIMESTAMP', false, null, null);
		$this->addColumn('DATE_SORTIE_GARAGE', 'DateSortieGarage', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
		$this->addRelation('TblFacture', 'TblFacture', RelationMap::MANY_TO_ONE, array('id_facture' => 'id_facture', ), null, null);
	} // buildRelations()

	/**
	 *
	 * Gets the list of behaviors registered for this table
	 *
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // TblTicketTableMap
