<?php



/**
 * This class defines the structure of the 'tbl_voiture' table.
 *
 *
 * This class was autogenerated by Propel 1.6.6-dev on:
 *
 * 01/09/14 10:18:29
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class TblVoitureTableMap extends TableMap
{

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.TblVoitureTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
		// attributes
		$this->setName('tbl_voiture');
		$this->setPhpName('TblVoiture');
		$this->setClassname('TblVoiture');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID_VOITURE', 'IdVoiture', 'INTEGER', true, null, null);
		$this->addForeignKey('ID_CLIENT', 'IdClient', 'INTEGER', 'tbl_client', 'ID_CLIENT', false, null, null);
		$this->addColumn('IMMATRICULATION', 'Immatriculation', 'VARCHAR', false, 100, null);
		$this->addForeignKey('ID_MARQUE', 'IdMarque', 'INTEGER', 'ref_marque', 'MARQUE_ID', false, null, null);
		$this->addForeignKey('ID_MOTORISATION', 'IdMotorisation', 'INTEGER', 'ref_motorisation', 'ID_MOTORISATION', false, null, null);
		$this->addColumn('COULEUR', 'Couleur', 'VARCHAR', false, 30, null);
		$this->addForeignKey('NBR_PORTES', 'NbrPortes', 'INTEGER', 'ref_nbr_portes', 'ID_NBR_PORTES', false, null, null);
		$this->addColumn('MODELE', 'Modele', 'VARCHAR', false, 100, null);
		$this->addColumn('ANNEE', 'Annee', 'INTEGER', false, null, null);
		$this->addColumn('NB_VISITE', 'NbVisite', 'INTEGER', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
		$this->addRelation('TblClient', 'TblClient', RelationMap::MANY_TO_ONE, array('id_client' => 'id_client', ), null, null);
		$this->addRelation('RefMarque', 'RefMarque', RelationMap::MANY_TO_ONE, array('id_marque' => 'marque_id', ), null, null);
		$this->addRelation('RefMotorisation', 'RefMotorisation', RelationMap::MANY_TO_ONE, array('id_motorisation' => 'id_motorisation', ), null, null);
		$this->addRelation('RefNbrPortes', 'RefNbrPortes', RelationMap::MANY_TO_ONE, array('nbr_portes' => 'id_nbr_portes', ), null, null);
		$this->addRelation('TblFacture', 'TblFacture', RelationMap::ONE_TO_MANY, array('id_voiture' => 'id_voiture', ), null, null, 'TblFactures');
	} // buildRelations()

	/**
	 *
	 * Gets the list of behaviors registered for this table
	 *
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // TblVoitureTableMap
