newTapisSuccess:
  stylesheets: 
    - ui-lightness/jquery-ui-1.8.17.custom.css
  javascripts: [ bootstrap/moment.min.js, jquery-1.5.2.min.js ]
editSuccess:
  stylesheets: 
    - ui-lightness/jquery-ui-1.8.17.custom.css
    
    
listeTapisSuccess:
  javascripts:
    - jquery.dataTables.min.js
    - jquery.plugins.js
    - jquery-ui.js
    - jscolor.js
  stylesheets: [ dataTable/table_jui.css , ui-lightness/jquery-ui-1.8.17.custom.css , -forFormulaire.css ]      