<?php


/**
 * Base class that represents a query for the 'tbl_ticket' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.6-dev on:
 *
 * 03/05/14 22:48:08
 *
 * @method     TblTicketQuery orderByIdTicket($order = Criteria::ASC) Order by the id_ticket column
 * @method     TblTicketQuery orderByIdFacture($order = Criteria::ASC) Order by the id_facture column
 * @method     TblTicketQuery orderByDateEntreeGarage($order = Criteria::ASC) Order by the date_entree_garage column
 * @method     TblTicketQuery orderByDateSortieGarage($order = Criteria::ASC) Order by the date_sortie_garage column
 *
 * @method     TblTicketQuery groupByIdTicket() Group by the id_ticket column
 * @method     TblTicketQuery groupByIdFacture() Group by the id_facture column
 * @method     TblTicketQuery groupByDateEntreeGarage() Group by the date_entree_garage column
 * @method     TblTicketQuery groupByDateSortieGarage() Group by the date_sortie_garage column
 *
 * @method     TblTicketQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     TblTicketQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     TblTicketQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     TblTicketQuery leftJoinTblFacture($relationAlias = null) Adds a LEFT JOIN clause to the query using the TblFacture relation
 * @method     TblTicketQuery rightJoinTblFacture($relationAlias = null) Adds a RIGHT JOIN clause to the query using the TblFacture relation
 * @method     TblTicketQuery innerJoinTblFacture($relationAlias = null) Adds a INNER JOIN clause to the query using the TblFacture relation
 *
 * @method     TblTicket findOne(PropelPDO $con = null) Return the first TblTicket matching the query
 * @method     TblTicket findOneOrCreate(PropelPDO $con = null) Return the first TblTicket matching the query, or a new TblTicket object populated from the query conditions when no match is found
 *
 * @method     TblTicket findOneByIdTicket(int $id_ticket) Return the first TblTicket filtered by the id_ticket column
 * @method     TblTicket findOneByIdFacture(int $id_facture) Return the first TblTicket filtered by the id_facture column
 * @method     TblTicket findOneByDateEntreeGarage(string $date_entree_garage) Return the first TblTicket filtered by the date_entree_garage column
 * @method     TblTicket findOneByDateSortieGarage(string $date_sortie_garage) Return the first TblTicket filtered by the date_sortie_garage column
 *
 * @method     array findByIdTicket(int $id_ticket) Return TblTicket objects filtered by the id_ticket column
 * @method     array findByIdFacture(int $id_facture) Return TblTicket objects filtered by the id_facture column
 * @method     array findByDateEntreeGarage(string $date_entree_garage) Return TblTicket objects filtered by the date_entree_garage column
 * @method     array findByDateSortieGarage(string $date_sortie_garage) Return TblTicket objects filtered by the date_sortie_garage column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseTblTicketQuery extends ModelCriteria
{
	
	/**
	 * Initializes internal state of BaseTblTicketQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'TblTicket', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new TblTicketQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    TblTicketQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof TblTicketQuery) {
			return $criteria;
		}
		$query = new TblTicketQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key.
	 * Propel uses the instance pool to skip the database if the object exists.
	 * Go fast if the query is untouched.
	 *
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 *
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    TblTicket|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ($key === null) {
			return null;
		}
		if ((null !== ($obj = TblTicketPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
			// the object is alredy in the instance pool
			return $obj;
		}
		if ($con === null) {
			$con = Propel::getConnection(TblTicketPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		$this->basePreSelect($con);
		if ($this->formatter || $this->modelAlias || $this->with || $this->select
		 || $this->selectColumns || $this->asColumns || $this->selectModifiers
		 || $this->map || $this->having || $this->joins) {
			return $this->findPkComplex($key, $con);
		} else {
			return $this->findPkSimple($key, $con);
		}
	}

	/**
	 * Find object by primary key using raw SQL to go fast.
	 * Bypass doSelect() and the object formatter by using generated code.
	 *
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con A connection object
	 *
	 * @return    TblTicket A model object, or null if the key is not found
	 */
	protected function findPkSimple($key, $con)
	{
		$sql = 'SELECT `ID_TICKET`, `ID_FACTURE`, `DATE_ENTREE_GARAGE`, `DATE_SORTIE_GARAGE` FROM `tbl_ticket` WHERE `ID_TICKET` = :p0';
		try {
			$stmt = $con->prepare($sql);
			$stmt->bindValue(':p0', $key, PDO::PARAM_INT);
			$stmt->execute();
		} catch (Exception $e) {
			Propel::log($e->getMessage(), Propel::LOG_ERR);
			throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
		}
		$obj = null;
		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$obj = new TblTicket();
			$obj->hydrate($row);
			TblTicketPeer::addInstanceToPool($obj, (string) $key);
		}
		$stmt->closeCursor();

		return $obj;
	}

	/**
	 * Find object by primary key.
	 *
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con A connection object
	 *
	 * @return    TblTicket|array|mixed the result, formatted by the current formatter
	 */
	protected function findPkComplex($key, $con)
	{
		// As the query uses a PK condition, no limit(1) is necessary.
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		$stmt = $criteria
			->filterByPrimaryKey($key)
			->doSelect($con);
		return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
		}
		$this->basePreSelect($con);
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		$stmt = $criteria
			->filterByPrimaryKeys($keys)
			->doSelect($con);
		return $criteria->getFormatter()->init($criteria)->format($stmt);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    TblTicketQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(TblTicketPeer::ID_TICKET, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    TblTicketQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(TblTicketPeer::ID_TICKET, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the id_ticket column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByIdTicket(1234); // WHERE id_ticket = 1234
	 * $query->filterByIdTicket(array(12, 34)); // WHERE id_ticket IN (12, 34)
	 * $query->filterByIdTicket(array('min' => 12)); // WHERE id_ticket > 12
	 * </code>
	 *
	 * @param     mixed $idTicket The value to use as filter.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    TblTicketQuery The current query, for fluid interface
	 */
	public function filterByIdTicket($idTicket = null, $comparison = null)
	{
		if (is_array($idTicket) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(TblTicketPeer::ID_TICKET, $idTicket, $comparison);
	}

	/**
	 * Filter the query on the id_facture column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByIdFacture(1234); // WHERE id_facture = 1234
	 * $query->filterByIdFacture(array(12, 34)); // WHERE id_facture IN (12, 34)
	 * $query->filterByIdFacture(array('min' => 12)); // WHERE id_facture > 12
	 * </code>
	 *
	 * @see       filterByTblFacture()
	 *
	 * @param     mixed $idFacture The value to use as filter.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    TblTicketQuery The current query, for fluid interface
	 */
	public function filterByIdFacture($idFacture = null, $comparison = null)
	{
		if (is_array($idFacture)) {
			$useMinMax = false;
			if (isset($idFacture['min'])) {
				$this->addUsingAlias(TblTicketPeer::ID_FACTURE, $idFacture['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($idFacture['max'])) {
				$this->addUsingAlias(TblTicketPeer::ID_FACTURE, $idFacture['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(TblTicketPeer::ID_FACTURE, $idFacture, $comparison);
	}

	/**
	 * Filter the query on the date_entree_garage column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByDateEntreeGarage('2011-03-14'); // WHERE date_entree_garage = '2011-03-14'
	 * $query->filterByDateEntreeGarage('now'); // WHERE date_entree_garage = '2011-03-14'
	 * $query->filterByDateEntreeGarage(array('max' => 'yesterday')); // WHERE date_entree_garage > '2011-03-13'
	 * </code>
	 *
	 * @param     mixed $dateEntreeGarage The value to use as filter.
	 *              Values can be integers (unix timestamps), DateTime objects, or strings.
	 *              Empty strings are treated as NULL.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    TblTicketQuery The current query, for fluid interface
	 */
	public function filterByDateEntreeGarage($dateEntreeGarage = null, $comparison = null)
	{
		if (is_array($dateEntreeGarage)) {
			$useMinMax = false;
			if (isset($dateEntreeGarage['min'])) {
				$this->addUsingAlias(TblTicketPeer::DATE_ENTREE_GARAGE, $dateEntreeGarage['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($dateEntreeGarage['max'])) {
				$this->addUsingAlias(TblTicketPeer::DATE_ENTREE_GARAGE, $dateEntreeGarage['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(TblTicketPeer::DATE_ENTREE_GARAGE, $dateEntreeGarage, $comparison);
	}

	/**
	 * Filter the query on the date_sortie_garage column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByDateSortieGarage('2011-03-14'); // WHERE date_sortie_garage = '2011-03-14'
	 * $query->filterByDateSortieGarage('now'); // WHERE date_sortie_garage = '2011-03-14'
	 * $query->filterByDateSortieGarage(array('max' => 'yesterday')); // WHERE date_sortie_garage > '2011-03-13'
	 * </code>
	 *
	 * @param     mixed $dateSortieGarage The value to use as filter.
	 *              Values can be integers (unix timestamps), DateTime objects, or strings.
	 *              Empty strings are treated as NULL.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    TblTicketQuery The current query, for fluid interface
	 */
	public function filterByDateSortieGarage($dateSortieGarage = null, $comparison = null)
	{
		if (is_array($dateSortieGarage)) {
			$useMinMax = false;
			if (isset($dateSortieGarage['min'])) {
				$this->addUsingAlias(TblTicketPeer::DATE_SORTIE_GARAGE, $dateSortieGarage['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($dateSortieGarage['max'])) {
				$this->addUsingAlias(TblTicketPeer::DATE_SORTIE_GARAGE, $dateSortieGarage['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(TblTicketPeer::DATE_SORTIE_GARAGE, $dateSortieGarage, $comparison);
	}

	/**
	 * Filter the query by a related TblFacture object
	 *
	 * @param     TblFacture|PropelCollection $tblFacture The related object(s) to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    TblTicketQuery The current query, for fluid interface
	 */
	public function filterByTblFacture($tblFacture, $comparison = null)
	{
		if ($tblFacture instanceof TblFacture) {
			return $this
				->addUsingAlias(TblTicketPeer::ID_FACTURE, $tblFacture->getIdFacture(), $comparison);
		} elseif ($tblFacture instanceof PropelCollection) {
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
			return $this
				->addUsingAlias(TblTicketPeer::ID_FACTURE, $tblFacture->toKeyValue('PrimaryKey', 'IdFacture'), $comparison);
		} else {
			throw new PropelException('filterByTblFacture() only accepts arguments of type TblFacture or PropelCollection');
		}
	}

	/**
	 * Adds a JOIN clause to the query using the TblFacture relation
	 *
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    TblTicketQuery The current query, for fluid interface
	 */
	public function joinTblFacture($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('TblFacture');

		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}

		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'TblFacture');
		}

		return $this;
	}

	/**
	 * Use the TblFacture relation TblFacture object
	 *
	 * @see       useQuery()
	 *
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    TblFactureQuery A secondary query class using the current class as primary query
	 */
	public function useTblFactureQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
	{
		return $this
			->joinTblFacture($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'TblFacture', 'TblFactureQuery');
	}

	/**
	 * Exclude object from result
	 *
	 * @param     TblTicket $tblTicket Object to remove from the list of results
	 *
	 * @return    TblTicketQuery The current query, for fluid interface
	 */
	public function prune($tblTicket = null)
	{
		if ($tblTicket) {
			$this->addUsingAlias(TblTicketPeer::ID_TICKET, $tblTicket->getIdTicket(), Criteria::NOT_EQUAL);
		}

		return $this;
	}

} // BaseTblTicketQuery