<?php


/**
 * Base class that represents a query for the 'tbl_facture' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.6-dev on:
 *
 * 03/21/14 17:07:52
 *
 * @method     TblFactureQuery orderByIdFacture($order = Criteria::ASC) Order by the id_facture column
 * @method     TblFactureQuery orderByIdVoiture($order = Criteria::ASC) Order by the id_voiture column
 * @method     TblFactureQuery orderByIdEmploye($order = Criteria::ASC) Order by the id_employe column
 * @method     TblFactureQuery orderByPrixLavage($order = Criteria::ASC) Order by the prix_lavage column
 * @method     TblFactureQuery orderByCommentaireReglement($order = Criteria::ASC) Order by the commentaire_reglement column
 * @method     TblFactureQuery orderByDateReglement($order = Criteria::ASC) Order by the date_reglement column
 * @method     TblFactureQuery orderByEtat($order = Criteria::ASC) Order by the etat column
 * @method     TblFactureQuery orderByCreatedAt($order = Criteria::ASC) Order by the created_at column
 * @method     TblFactureQuery orderByUpdatedAt($order = Criteria::ASC) Order by the updated_at column
 * @method     TblFactureQuery orderByDeletedAt($order = Criteria::ASC) Order by the deleted_at column
 *
 * @method     TblFactureQuery groupByIdFacture() Group by the id_facture column
 * @method     TblFactureQuery groupByIdVoiture() Group by the id_voiture column
 * @method     TblFactureQuery groupByIdEmploye() Group by the id_employe column
 * @method     TblFactureQuery groupByPrixLavage() Group by the prix_lavage column
 * @method     TblFactureQuery groupByCommentaireReglement() Group by the commentaire_reglement column
 * @method     TblFactureQuery groupByDateReglement() Group by the date_reglement column
 * @method     TblFactureQuery groupByEtat() Group by the etat column
 * @method     TblFactureQuery groupByCreatedAt() Group by the created_at column
 * @method     TblFactureQuery groupByUpdatedAt() Group by the updated_at column
 * @method     TblFactureQuery groupByDeletedAt() Group by the deleted_at column
 *
 * @method     TblFactureQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     TblFactureQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     TblFactureQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     TblFactureQuery leftJoinTblVoiture($relationAlias = null) Adds a LEFT JOIN clause to the query using the TblVoiture relation
 * @method     TblFactureQuery rightJoinTblVoiture($relationAlias = null) Adds a RIGHT JOIN clause to the query using the TblVoiture relation
 * @method     TblFactureQuery innerJoinTblVoiture($relationAlias = null) Adds a INNER JOIN clause to the query using the TblVoiture relation
 *
 * @method     TblFactureQuery leftJoinTblClient($relationAlias = null) Adds a LEFT JOIN clause to the query using the TblClient relation
 * @method     TblFactureQuery rightJoinTblClient($relationAlias = null) Adds a RIGHT JOIN clause to the query using the TblClient relation
 * @method     TblFactureQuery innerJoinTblClient($relationAlias = null) Adds a INNER JOIN clause to the query using the TblClient relation
 *
 * @method     TblFactureQuery leftJoinLnkTypeLavageFacture($relationAlias = null) Adds a LEFT JOIN clause to the query using the LnkTypeLavageFacture relation
 * @method     TblFactureQuery rightJoinLnkTypeLavageFacture($relationAlias = null) Adds a RIGHT JOIN clause to the query using the LnkTypeLavageFacture relation
 * @method     TblFactureQuery innerJoinLnkTypeLavageFacture($relationAlias = null) Adds a INNER JOIN clause to the query using the LnkTypeLavageFacture relation
 *
 * @method     TblFactureQuery leftJoinTblTicket($relationAlias = null) Adds a LEFT JOIN clause to the query using the TblTicket relation
 * @method     TblFactureQuery rightJoinTblTicket($relationAlias = null) Adds a RIGHT JOIN clause to the query using the TblTicket relation
 * @method     TblFactureQuery innerJoinTblTicket($relationAlias = null) Adds a INNER JOIN clause to the query using the TblTicket relation
 *
 * @method     TblFacture findOne(PropelPDO $con = null) Return the first TblFacture matching the query
 * @method     TblFacture findOneOrCreate(PropelPDO $con = null) Return the first TblFacture matching the query, or a new TblFacture object populated from the query conditions when no match is found
 *
 * @method     TblFacture findOneByIdFacture(int $id_facture) Return the first TblFacture filtered by the id_facture column
 * @method     TblFacture findOneByIdVoiture(int $id_voiture) Return the first TblFacture filtered by the id_voiture column
 * @method     TblFacture findOneByIdEmploye(int $id_employe) Return the first TblFacture filtered by the id_employe column
 * @method     TblFacture findOneByPrixLavage(double $prix_lavage) Return the first TblFacture filtered by the prix_lavage column
 * @method     TblFacture findOneByCommentaireReglement(string $commentaire_reglement) Return the first TblFacture filtered by the commentaire_reglement column
 * @method     TblFacture findOneByDateReglement(string $date_reglement) Return the first TblFacture filtered by the date_reglement column
 * @method     TblFacture findOneByEtat(boolean $etat) Return the first TblFacture filtered by the etat column
 * @method     TblFacture findOneByCreatedAt(string $created_at) Return the first TblFacture filtered by the created_at column
 * @method     TblFacture findOneByUpdatedAt(string $updated_at) Return the first TblFacture filtered by the updated_at column
 * @method     TblFacture findOneByDeletedAt(string $deleted_at) Return the first TblFacture filtered by the deleted_at column
 *
 * @method     array findByIdFacture(int $id_facture) Return TblFacture objects filtered by the id_facture column
 * @method     array findByIdVoiture(int $id_voiture) Return TblFacture objects filtered by the id_voiture column
 * @method     array findByIdEmploye(int $id_employe) Return TblFacture objects filtered by the id_employe column
 * @method     array findByPrixLavage(double $prix_lavage) Return TblFacture objects filtered by the prix_lavage column
 * @method     array findByCommentaireReglement(string $commentaire_reglement) Return TblFacture objects filtered by the commentaire_reglement column
 * @method     array findByDateReglement(string $date_reglement) Return TblFacture objects filtered by the date_reglement column
 * @method     array findByEtat(boolean $etat) Return TblFacture objects filtered by the etat column
 * @method     array findByCreatedAt(string $created_at) Return TblFacture objects filtered by the created_at column
 * @method     array findByUpdatedAt(string $updated_at) Return TblFacture objects filtered by the updated_at column
 * @method     array findByDeletedAt(string $deleted_at) Return TblFacture objects filtered by the deleted_at column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseTblFactureQuery extends ModelCriteria
{
	
	// soft_delete behavior
	protected static $softDelete = true;
	protected $localSoftDelete = true;

	/**
	 * Initializes internal state of BaseTblFactureQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'TblFacture', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new TblFactureQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    TblFactureQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof TblFactureQuery) {
			return $criteria;
		}
		$query = new TblFactureQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key.
	 * Propel uses the instance pool to skip the database if the object exists.
	 * Go fast if the query is untouched.
	 *
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 *
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    TblFacture|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ($key === null) {
			return null;
		}
		if ((null !== ($obj = TblFacturePeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
			// the object is alredy in the instance pool
			return $obj;
		}
		if ($con === null) {
			$con = Propel::getConnection(TblFacturePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		$this->basePreSelect($con);
		if ($this->formatter || $this->modelAlias || $this->with || $this->select
		 || $this->selectColumns || $this->asColumns || $this->selectModifiers
		 || $this->map || $this->having || $this->joins) {
			return $this->findPkComplex($key, $con);
		} else {
			return $this->findPkSimple($key, $con);
		}
	}

	/**
	 * Find object by primary key using raw SQL to go fast.
	 * Bypass doSelect() and the object formatter by using generated code.
	 *
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con A connection object
	 *
	 * @return    TblFacture A model object, or null if the key is not found
	 */
	protected function findPkSimple($key, $con)
	{
		$sql = 'SELECT `ID_FACTURE`, `ID_VOITURE`, `ID_EMPLOYE`, `PRIX_LAVAGE`, `COMMENTAIRE_REGLEMENT`, `DATE_REGLEMENT`, `ETAT`, `CREATED_AT`, `UPDATED_AT`, `DELETED_AT` FROM `tbl_facture` WHERE `ID_FACTURE` = :p0';
		try {
			$stmt = $con->prepare($sql);
			$stmt->bindValue(':p0', $key, PDO::PARAM_INT);
			$stmt->execute();
		} catch (Exception $e) {
			Propel::log($e->getMessage(), Propel::LOG_ERR);
			throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
		}
		$obj = null;
		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$obj = new TblFacture();
			$obj->hydrate($row);
			TblFacturePeer::addInstanceToPool($obj, (string) $key);
		}
		$stmt->closeCursor();

		return $obj;
	}

	/**
	 * Find object by primary key.
	 *
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con A connection object
	 *
	 * @return    TblFacture|array|mixed the result, formatted by the current formatter
	 */
	protected function findPkComplex($key, $con)
	{
		// As the query uses a PK condition, no limit(1) is necessary.
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		$stmt = $criteria
			->filterByPrimaryKey($key)
			->doSelect($con);
		return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
		}
		$this->basePreSelect($con);
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		$stmt = $criteria
			->filterByPrimaryKeys($keys)
			->doSelect($con);
		return $criteria->getFormatter()->init($criteria)->format($stmt);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    TblFactureQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(TblFacturePeer::ID_FACTURE, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    TblFactureQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(TblFacturePeer::ID_FACTURE, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the id_facture column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByIdFacture(1234); // WHERE id_facture = 1234
	 * $query->filterByIdFacture(array(12, 34)); // WHERE id_facture IN (12, 34)
	 * $query->filterByIdFacture(array('min' => 12)); // WHERE id_facture > 12
	 * </code>
	 *
	 * @param     mixed $idFacture The value to use as filter.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    TblFactureQuery The current query, for fluid interface
	 */
	public function filterByIdFacture($idFacture = null, $comparison = null)
	{
		if (is_array($idFacture) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(TblFacturePeer::ID_FACTURE, $idFacture, $comparison);
	}

	/**
	 * Filter the query on the id_voiture column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByIdVoiture(1234); // WHERE id_voiture = 1234
	 * $query->filterByIdVoiture(array(12, 34)); // WHERE id_voiture IN (12, 34)
	 * $query->filterByIdVoiture(array('min' => 12)); // WHERE id_voiture > 12
	 * </code>
	 *
	 * @see       filterByTblVoiture()
	 *
	 * @param     mixed $idVoiture The value to use as filter.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    TblFactureQuery The current query, for fluid interface
	 */
	public function filterByIdVoiture($idVoiture = null, $comparison = null)
	{
		if (is_array($idVoiture)) {
			$useMinMax = false;
			if (isset($idVoiture['min'])) {
				$this->addUsingAlias(TblFacturePeer::ID_VOITURE, $idVoiture['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($idVoiture['max'])) {
				$this->addUsingAlias(TblFacturePeer::ID_VOITURE, $idVoiture['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(TblFacturePeer::ID_VOITURE, $idVoiture, $comparison);
	}

	/**
	 * Filter the query on the id_employe column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByIdEmploye(1234); // WHERE id_employe = 1234
	 * $query->filterByIdEmploye(array(12, 34)); // WHERE id_employe IN (12, 34)
	 * $query->filterByIdEmploye(array('min' => 12)); // WHERE id_employe > 12
	 * </code>
	 *
	 * @see       filterByTblClient()
	 *
	 * @param     mixed $idEmploye The value to use as filter.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    TblFactureQuery The current query, for fluid interface
	 */
	public function filterByIdEmploye($idEmploye = null, $comparison = null)
	{
		if (is_array($idEmploye)) {
			$useMinMax = false;
			if (isset($idEmploye['min'])) {
				$this->addUsingAlias(TblFacturePeer::ID_EMPLOYE, $idEmploye['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($idEmploye['max'])) {
				$this->addUsingAlias(TblFacturePeer::ID_EMPLOYE, $idEmploye['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(TblFacturePeer::ID_EMPLOYE, $idEmploye, $comparison);
	}

	/**
	 * Filter the query on the prix_lavage column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByPrixLavage(1234); // WHERE prix_lavage = 1234
	 * $query->filterByPrixLavage(array(12, 34)); // WHERE prix_lavage IN (12, 34)
	 * $query->filterByPrixLavage(array('min' => 12)); // WHERE prix_lavage > 12
	 * </code>
	 *
	 * @param     mixed $prixLavage The value to use as filter.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    TblFactureQuery The current query, for fluid interface
	 */
	public function filterByPrixLavage($prixLavage = null, $comparison = null)
	{
		if (is_array($prixLavage)) {
			$useMinMax = false;
			if (isset($prixLavage['min'])) {
				$this->addUsingAlias(TblFacturePeer::PRIX_LAVAGE, $prixLavage['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($prixLavage['max'])) {
				$this->addUsingAlias(TblFacturePeer::PRIX_LAVAGE, $prixLavage['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(TblFacturePeer::PRIX_LAVAGE, $prixLavage, $comparison);
	}

	/**
	 * Filter the query on the commentaire_reglement column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByCommentaireReglement('fooValue');   // WHERE commentaire_reglement = 'fooValue'
	 * $query->filterByCommentaireReglement('%fooValue%'); // WHERE commentaire_reglement LIKE '%fooValue%'
	 * </code>
	 *
	 * @param     string $commentaireReglement The value to use as filter.
	 *              Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    TblFactureQuery The current query, for fluid interface
	 */
	public function filterByCommentaireReglement($commentaireReglement = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($commentaireReglement)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $commentaireReglement)) {
				$commentaireReglement = str_replace('*', '%', $commentaireReglement);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(TblFacturePeer::COMMENTAIRE_REGLEMENT, $commentaireReglement, $comparison);
	}

	/**
	 * Filter the query on the date_reglement column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByDateReglement('2011-03-14'); // WHERE date_reglement = '2011-03-14'
	 * $query->filterByDateReglement('now'); // WHERE date_reglement = '2011-03-14'
	 * $query->filterByDateReglement(array('max' => 'yesterday')); // WHERE date_reglement > '2011-03-13'
	 * </code>
	 *
	 * @param     mixed $dateReglement The value to use as filter.
	 *              Values can be integers (unix timestamps), DateTime objects, or strings.
	 *              Empty strings are treated as NULL.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    TblFactureQuery The current query, for fluid interface
	 */
	public function filterByDateReglement($dateReglement = null, $comparison = null)
	{
		if (is_array($dateReglement)) {
			$useMinMax = false;
			if (isset($dateReglement['min'])) {
				$this->addUsingAlias(TblFacturePeer::DATE_REGLEMENT, $dateReglement['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($dateReglement['max'])) {
				$this->addUsingAlias(TblFacturePeer::DATE_REGLEMENT, $dateReglement['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(TblFacturePeer::DATE_REGLEMENT, $dateReglement, $comparison);
	}

	/**
	 * Filter the query on the etat column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByEtat(true); // WHERE etat = true
	 * $query->filterByEtat('yes'); // WHERE etat = true
	 * </code>
	 *
	 * @param     boolean|string $etat The value to use as filter.
	 *              Non-boolean arguments are converted using the following rules:
	 *                * 1, '1', 'true',  'on',  and 'yes' are converted to boolean true
	 *                * 0, '0', 'false', 'off', and 'no'  are converted to boolean false
	 *              Check on string values is case insensitive (so 'FaLsE' is seen as 'false').
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    TblFactureQuery The current query, for fluid interface
	 */
	public function filterByEtat($etat = null, $comparison = null)
	{
		if (is_string($etat)) {
			$etat = in_array(strtolower($etat), array('false', 'off', '-', 'no', 'n', '0', '')) ? false : true;
		}
		return $this->addUsingAlias(TblFacturePeer::ETAT, $etat, $comparison);
	}

	/**
	 * Filter the query on the created_at column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByCreatedAt('2011-03-14'); // WHERE created_at = '2011-03-14'
	 * $query->filterByCreatedAt('now'); // WHERE created_at = '2011-03-14'
	 * $query->filterByCreatedAt(array('max' => 'yesterday')); // WHERE created_at > '2011-03-13'
	 * </code>
	 *
	 * @param     mixed $createdAt The value to use as filter.
	 *              Values can be integers (unix timestamps), DateTime objects, or strings.
	 *              Empty strings are treated as NULL.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    TblFactureQuery The current query, for fluid interface
	 */
	public function filterByCreatedAt($createdAt = null, $comparison = null)
	{
		if (is_array($createdAt)) {
			$useMinMax = false;
			if (isset($createdAt['min'])) {
				$this->addUsingAlias(TblFacturePeer::CREATED_AT, $createdAt['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($createdAt['max'])) {
				$this->addUsingAlias(TblFacturePeer::CREATED_AT, $createdAt['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(TblFacturePeer::CREATED_AT, $createdAt, $comparison);
	}

	/**
	 * Filter the query on the updated_at column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByUpdatedAt('2011-03-14'); // WHERE updated_at = '2011-03-14'
	 * $query->filterByUpdatedAt('now'); // WHERE updated_at = '2011-03-14'
	 * $query->filterByUpdatedAt(array('max' => 'yesterday')); // WHERE updated_at > '2011-03-13'
	 * </code>
	 *
	 * @param     mixed $updatedAt The value to use as filter.
	 *              Values can be integers (unix timestamps), DateTime objects, or strings.
	 *              Empty strings are treated as NULL.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    TblFactureQuery The current query, for fluid interface
	 */
	public function filterByUpdatedAt($updatedAt = null, $comparison = null)
	{
		if (is_array($updatedAt)) {
			$useMinMax = false;
			if (isset($updatedAt['min'])) {
				$this->addUsingAlias(TblFacturePeer::UPDATED_AT, $updatedAt['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($updatedAt['max'])) {
				$this->addUsingAlias(TblFacturePeer::UPDATED_AT, $updatedAt['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(TblFacturePeer::UPDATED_AT, $updatedAt, $comparison);
	}

	/**
	 * Filter the query on the deleted_at column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByDeletedAt('2011-03-14'); // WHERE deleted_at = '2011-03-14'
	 * $query->filterByDeletedAt('now'); // WHERE deleted_at = '2011-03-14'
	 * $query->filterByDeletedAt(array('max' => 'yesterday')); // WHERE deleted_at > '2011-03-13'
	 * </code>
	 *
	 * @param     mixed $deletedAt The value to use as filter.
	 *              Values can be integers (unix timestamps), DateTime objects, or strings.
	 *              Empty strings are treated as NULL.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    TblFactureQuery The current query, for fluid interface
	 */
	public function filterByDeletedAt($deletedAt = null, $comparison = null)
	{
		if (is_array($deletedAt)) {
			$useMinMax = false;
			if (isset($deletedAt['min'])) {
				$this->addUsingAlias(TblFacturePeer::DELETED_AT, $deletedAt['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($deletedAt['max'])) {
				$this->addUsingAlias(TblFacturePeer::DELETED_AT, $deletedAt['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(TblFacturePeer::DELETED_AT, $deletedAt, $comparison);
	}

	/**
	 * Filter the query by a related TblVoiture object
	 *
	 * @param     TblVoiture|PropelCollection $tblVoiture The related object(s) to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    TblFactureQuery The current query, for fluid interface
	 */
	public function filterByTblVoiture($tblVoiture, $comparison = null)
	{
		if ($tblVoiture instanceof TblVoiture) {
			return $this
				->addUsingAlias(TblFacturePeer::ID_VOITURE, $tblVoiture->getIdVoiture(), $comparison);
		} elseif ($tblVoiture instanceof PropelCollection) {
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
			return $this
				->addUsingAlias(TblFacturePeer::ID_VOITURE, $tblVoiture->toKeyValue('PrimaryKey', 'IdVoiture'), $comparison);
		} else {
			throw new PropelException('filterByTblVoiture() only accepts arguments of type TblVoiture or PropelCollection');
		}
	}

	/**
	 * Adds a JOIN clause to the query using the TblVoiture relation
	 *
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    TblFactureQuery The current query, for fluid interface
	 */
	public function joinTblVoiture($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('TblVoiture');

		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}

		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'TblVoiture');
		}

		return $this;
	}

	/**
	 * Use the TblVoiture relation TblVoiture object
	 *
	 * @see       useQuery()
	 *
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    TblVoitureQuery A secondary query class using the current class as primary query
	 */
	public function useTblVoitureQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
	{
		return $this
			->joinTblVoiture($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'TblVoiture', 'TblVoitureQuery');
	}

	/**
	 * Filter the query by a related TblClient object
	 *
	 * @param     TblClient|PropelCollection $tblClient The related object(s) to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    TblFactureQuery The current query, for fluid interface
	 */
	public function filterByTblClient($tblClient, $comparison = null)
	{
		if ($tblClient instanceof TblClient) {
			return $this
				->addUsingAlias(TblFacturePeer::ID_EMPLOYE, $tblClient->getIdClient(), $comparison);
		} elseif ($tblClient instanceof PropelCollection) {
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
			return $this
				->addUsingAlias(TblFacturePeer::ID_EMPLOYE, $tblClient->toKeyValue('PrimaryKey', 'IdClient'), $comparison);
		} else {
			throw new PropelException('filterByTblClient() only accepts arguments of type TblClient or PropelCollection');
		}
	}

	/**
	 * Adds a JOIN clause to the query using the TblClient relation
	 *
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    TblFactureQuery The current query, for fluid interface
	 */
	public function joinTblClient($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('TblClient');

		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}

		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'TblClient');
		}

		return $this;
	}

	/**
	 * Use the TblClient relation TblClient object
	 *
	 * @see       useQuery()
	 *
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    TblClientQuery A secondary query class using the current class as primary query
	 */
	public function useTblClientQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
	{
		return $this
			->joinTblClient($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'TblClient', 'TblClientQuery');
	}

	/**
	 * Filter the query by a related LnkTypeLavageFacture object
	 *
	 * @param     LnkTypeLavageFacture $lnkTypeLavageFacture  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    TblFactureQuery The current query, for fluid interface
	 */
	public function filterByLnkTypeLavageFacture($lnkTypeLavageFacture, $comparison = null)
	{
		if ($lnkTypeLavageFacture instanceof LnkTypeLavageFacture) {
			return $this
				->addUsingAlias(TblFacturePeer::ID_FACTURE, $lnkTypeLavageFacture->getIdFacture(), $comparison);
		} elseif ($lnkTypeLavageFacture instanceof PropelCollection) {
			return $this
				->useLnkTypeLavageFactureQuery()
				->filterByPrimaryKeys($lnkTypeLavageFacture->getPrimaryKeys())
				->endUse();
		} else {
			throw new PropelException('filterByLnkTypeLavageFacture() only accepts arguments of type LnkTypeLavageFacture or PropelCollection');
		}
	}

	/**
	 * Adds a JOIN clause to the query using the LnkTypeLavageFacture relation
	 *
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    TblFactureQuery The current query, for fluid interface
	 */
	public function joinLnkTypeLavageFacture($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('LnkTypeLavageFacture');

		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}

		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'LnkTypeLavageFacture');
		}

		return $this;
	}

	/**
	 * Use the LnkTypeLavageFacture relation LnkTypeLavageFacture object
	 *
	 * @see       useQuery()
	 *
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    LnkTypeLavageFactureQuery A secondary query class using the current class as primary query
	 */
	public function useLnkTypeLavageFactureQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		return $this
			->joinLnkTypeLavageFacture($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'LnkTypeLavageFacture', 'LnkTypeLavageFactureQuery');
	}

	/**
	 * Filter the query by a related TblTicket object
	 *
	 * @param     TblTicket $tblTicket  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    TblFactureQuery The current query, for fluid interface
	 */
	public function filterByTblTicket($tblTicket, $comparison = null)
	{
		if ($tblTicket instanceof TblTicket) {
			return $this
				->addUsingAlias(TblFacturePeer::ID_FACTURE, $tblTicket->getIdFacture(), $comparison);
		} elseif ($tblTicket instanceof PropelCollection) {
			return $this
				->useTblTicketQuery()
				->filterByPrimaryKeys($tblTicket->getPrimaryKeys())
				->endUse();
		} else {
			throw new PropelException('filterByTblTicket() only accepts arguments of type TblTicket or PropelCollection');
		}
	}

	/**
	 * Adds a JOIN clause to the query using the TblTicket relation
	 *
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    TblFactureQuery The current query, for fluid interface
	 */
	public function joinTblTicket($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('TblTicket');

		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}

		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'TblTicket');
		}

		return $this;
	}

	/**
	 * Use the TblTicket relation TblTicket object
	 *
	 * @see       useQuery()
	 *
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    TblTicketQuery A secondary query class using the current class as primary query
	 */
	public function useTblTicketQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
	{
		return $this
			->joinTblTicket($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'TblTicket', 'TblTicketQuery');
	}

	/**
	 * Exclude object from result
	 *
	 * @param     TblFacture $tblFacture Object to remove from the list of results
	 *
	 * @return    TblFactureQuery The current query, for fluid interface
	 */
	public function prune($tblFacture = null)
	{
		if ($tblFacture) {
			$this->addUsingAlias(TblFacturePeer::ID_FACTURE, $tblFacture->getIdFacture(), Criteria::NOT_EQUAL);
		}

		return $this;
	}

	/**
	 * Code to execute before every SELECT statement
	 *
	 * @param     PropelPDO $con The connection object used by the query
	 */
	protected function basePreSelect(PropelPDO $con)
	{
		// soft_delete behavior
		if (TblFactureQuery::isSoftDeleteEnabled() && $this->localSoftDelete) {
			$this->addUsingAlias(TblFacturePeer::DELETED_AT, null, Criteria::ISNULL);
		} else {
			TblFacturePeer::enableSoftDelete();
		}

		return $this->preSelect($con);
	}

	/**
	 * Code to execute before every DELETE statement
	 *
	 * @param     PropelPDO $con The connection object used by the query
	 */
	protected function basePreDelete(PropelPDO $con)
	{
		// soft_delete behavior
		if (TblFactureQuery::isSoftDeleteEnabled() && $this->localSoftDelete) {
			return $this->softDelete($con);
		} else {
			return $this->hasWhereClause() ? $this->forceDelete($con) : $this->forceDeleteAll($con);
		}

		return $this->preDelete($con);
	}

	// soft_delete behavior
	
	/**
	 * Temporarily disable the filter on deleted rows
	 * Valid only for the current query
	 *
	 * @see TblFactureQuery::disableSoftDelete() to disable the filter for more than one query
	 *
	 * @return TblFactureQuery The current query, for fluid interface
	 */
	public function includeDeleted()
	{
		$this->localSoftDelete = false;
		return $this;
	}
	
	/**
	 * Soft delete the selected rows
	 *
	 * @param			PropelPDO $con an optional connection object
	 *
	 * @return		int Number of updated rows
	 */
	public function softDelete(PropelPDO $con = null)
	{
		return $this->update(array('DeletedAt' => time()), $con);
	}
	
	/**
	 * Bypass the soft_delete behavior and force a hard delete of the selected rows
	 *
	 * @param			PropelPDO $con an optional connection object
	 *
	 * @return		int Number of deleted rows
	 */
	public function forceDelete(PropelPDO $con = null)
	{
		return TblFacturePeer::doForceDelete($this, $con);
	}
	
	/**
	 * Bypass the soft_delete behavior and force a hard delete of all the rows
	 *
	 * @param			PropelPDO $con an optional connection object
	 *
	 * @return		int Number of deleted rows
	 */
	public function forceDeleteAll(PropelPDO $con = null)
	{
		return TblFacturePeer::doForceDeleteAll($con);}
	
	/**
	 * Undelete selected rows
	 *
	 * @param			PropelPDO $con an optional connection object
	 *
	 * @return		int The number of rows affected by this update and any referring fk objects' save() operations.
	 */
	public function unDelete(PropelPDO $con = null)
	{
		return $this->update(array('DeletedAt' => null), $con);
	}
	
	/**
	 * Enable the soft_delete behavior for this model
	 */
	public static function enableSoftDelete()
	{
		self::$softDelete = true;
	}
	
	/**
	 * Disable the soft_delete behavior for this model
	 */
	public static function disableSoftDelete()
	{
		self::$softDelete = false;
	}
	
	/**
	 * Check the soft_delete behavior for this model
	 *
	 * @return boolean true if the soft_delete behavior is enabled
	 */
	public static function isSoftDeleteEnabled()
	{
		return self::$softDelete;
	}

} // BaseTblFactureQuery