<?php


/**
 * Base class that represents a row from the 'tbl_voiture' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.6-dev on:
 *
 * 03/23/14 17:30:03
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseTblVoiture extends BaseObject  implements Persistent
{

	/**
	 * Peer class name
	 */
	const PEER = 'TblVoiturePeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        TblVoiturePeer
	 */
	protected static $peer;

	/**
	 * The flag var to prevent infinit loop in deep copy
	 * @var       boolean
	 */
	protected $startCopy = false;

	/**
	 * The value for the id_voiture field.
	 * @var        int
	 */
	protected $id_voiture;

	/**
	 * The value for the id_client field.
	 * @var        int
	 */
	protected $id_client;

	/**
	 * The value for the immatriculation field.
	 * @var        string
	 */
	protected $immatriculation;

	/**
	 * The value for the id_marque field.
	 * @var        int
	 */
	protected $id_marque;

	/**
	 * The value for the id_motorisation field.
	 * @var        int
	 */
	protected $id_motorisation;

	/**
	 * The value for the couleur field.
	 * @var        string
	 */
	protected $couleur;

	/**
	 * The value for the nbr_portes field.
	 * @var        int
	 */
	protected $nbr_portes;

	/**
	 * The value for the modele field.
	 * @var        string
	 */
	protected $modele;

	/**
	 * The value for the annee field.
	 * @var        int
	 */
	protected $annee;

	/**
	 * The value for the nb_visite field.
	 * @var        int
	 */
	protected $nb_visite;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the deleted_at field.
	 * @var        string
	 */
	protected $deleted_at;

	/**
	 * @var        TblClient
	 */
	protected $aTblClient;

	/**
	 * @var        RefMarque
	 */
	protected $aRefMarque;

	/**
	 * @var        RefMotorisation
	 */
	protected $aRefMotorisation;

	/**
	 * @var        RefNbrPortes
	 */
	protected $aRefNbrPortes;

	/**
	 * @var        array TblFacture[] Collection to store aggregation of TblFacture objects.
	 */
	protected $collTblFactures;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * An array of objects scheduled for deletion.
	 * @var		array
	 */
	protected $tblFacturesScheduledForDeletion = null;

	/**
	 * Get the [id_voiture] column value.
	 * 
	 * @return     int
	 */
	public function getIdVoiture()
	{
		return $this->id_voiture;
	}

	/**
	 * Get the [id_client] column value.
	 * 
	 * @return     int
	 */
	public function getIdClient()
	{
		return $this->id_client;
	}

	/**
	 * Get the [immatriculation] column value.
	 * 
	 * @return     string
	 */
	public function getImmatriculation()
	{
		return $this->immatriculation;
	}

	/**
	 * Get the [id_marque] column value.
	 * 
	 * @return     int
	 */
	public function getIdMarque()
	{
		return $this->id_marque;
	}

	/**
	 * Get the [id_motorisation] column value.
	 * 
	 * @return     int
	 */
	public function getIdMotorisation()
	{
		return $this->id_motorisation;
	}

	/**
	 * Get the [couleur] column value.
	 * 
	 * @return     string
	 */
	public function getCouleur()
	{
		return $this->couleur;
	}

	/**
	 * Get the [nbr_portes] column value.
	 * 
	 * @return     int
	 */
	public function getNbrPortes()
	{
		return $this->nbr_portes;
	}

	/**
	 * Get the [modele] column value.
	 * 
	 * @return     string
	 */
	public function getModele()
	{
		return $this->modele;
	}

	/**
	 * Get the [annee] column value.
	 * 
	 * @return     int
	 */
	public function getAnnee()
	{
		return $this->annee;
	}

	/**
	 * Get the [nb_visite] column value.
	 * 
	 * @return     int
	 */
	public function getNbVisite()
	{
		return $this->nb_visite;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [deleted_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDeletedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->deleted_at === null) {
			return null;
		}


		if ($this->deleted_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->deleted_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->deleted_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id_voiture] column.
	 * 
	 * @param      int $v new value
	 * @return     TblVoiture The current object (for fluent API support)
	 */
	public function setIdVoiture($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_voiture !== $v) {
			$this->id_voiture = $v;
			$this->modifiedColumns[] = TblVoiturePeer::ID_VOITURE;
		}

		return $this;
	} // setIdVoiture()

	/**
	 * Set the value of [id_client] column.
	 * 
	 * @param      int $v new value
	 * @return     TblVoiture The current object (for fluent API support)
	 */
	public function setIdClient($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_client !== $v) {
			$this->id_client = $v;
			$this->modifiedColumns[] = TblVoiturePeer::ID_CLIENT;
		}

		if ($this->aTblClient !== null && $this->aTblClient->getIdClient() !== $v) {
			$this->aTblClient = null;
		}

		return $this;
	} // setIdClient()

	/**
	 * Set the value of [immatriculation] column.
	 * 
	 * @param      string $v new value
	 * @return     TblVoiture The current object (for fluent API support)
	 */
	public function setImmatriculation($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->immatriculation !== $v) {
			$this->immatriculation = $v;
			$this->modifiedColumns[] = TblVoiturePeer::IMMATRICULATION;
		}

		return $this;
	} // setImmatriculation()

	/**
	 * Set the value of [id_marque] column.
	 * 
	 * @param      int $v new value
	 * @return     TblVoiture The current object (for fluent API support)
	 */
	public function setIdMarque($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_marque !== $v) {
			$this->id_marque = $v;
			$this->modifiedColumns[] = TblVoiturePeer::ID_MARQUE;
		}

		if ($this->aRefMarque !== null && $this->aRefMarque->getMarqueId() !== $v) {
			$this->aRefMarque = null;
		}

		return $this;
	} // setIdMarque()

	/**
	 * Set the value of [id_motorisation] column.
	 * 
	 * @param      int $v new value
	 * @return     TblVoiture The current object (for fluent API support)
	 */
	public function setIdMotorisation($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_motorisation !== $v) {
			$this->id_motorisation = $v;
			$this->modifiedColumns[] = TblVoiturePeer::ID_MOTORISATION;
		}

		if ($this->aRefMotorisation !== null && $this->aRefMotorisation->getIdMotorisation() !== $v) {
			$this->aRefMotorisation = null;
		}

		return $this;
	} // setIdMotorisation()

	/**
	 * Set the value of [couleur] column.
	 * 
	 * @param      string $v new value
	 * @return     TblVoiture The current object (for fluent API support)
	 */
	public function setCouleur($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->couleur !== $v) {
			$this->couleur = $v;
			$this->modifiedColumns[] = TblVoiturePeer::COULEUR;
		}

		return $this;
	} // setCouleur()

	/**
	 * Set the value of [nbr_portes] column.
	 * 
	 * @param      int $v new value
	 * @return     TblVoiture The current object (for fluent API support)
	 */
	public function setNbrPortes($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->nbr_portes !== $v) {
			$this->nbr_portes = $v;
			$this->modifiedColumns[] = TblVoiturePeer::NBR_PORTES;
		}

		if ($this->aRefNbrPortes !== null && $this->aRefNbrPortes->getIdNbrPortes() !== $v) {
			$this->aRefNbrPortes = null;
		}

		return $this;
	} // setNbrPortes()

	/**
	 * Set the value of [modele] column.
	 * 
	 * @param      string $v new value
	 * @return     TblVoiture The current object (for fluent API support)
	 */
	public function setModele($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->modele !== $v) {
			$this->modele = $v;
			$this->modifiedColumns[] = TblVoiturePeer::MODELE;
		}

		return $this;
	} // setModele()

	/**
	 * Set the value of [annee] column.
	 * 
	 * @param      int $v new value
	 * @return     TblVoiture The current object (for fluent API support)
	 */
	public function setAnnee($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->annee !== $v) {
			$this->annee = $v;
			$this->modifiedColumns[] = TblVoiturePeer::ANNEE;
		}

		return $this;
	} // setAnnee()

	/**
	 * Set the value of [nb_visite] column.
	 * 
	 * @param      int $v new value
	 * @return     TblVoiture The current object (for fluent API support)
	 */
	public function setNbVisite($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->nb_visite !== $v) {
			$this->nb_visite = $v;
			$this->modifiedColumns[] = TblVoiturePeer::NB_VISITE;
		}

		return $this;
	} // setNbVisite()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.
	 *               Empty strings are treated as NULL.
	 * @return     TblVoiture The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		$dt = PropelDateTime::newInstance($v, null, 'DateTime');
		if ($this->created_at !== null || $dt !== null) {
			$currentDateAsString = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newDateAsString = $dt ? $dt->format('Y-m-d H:i:s') : null;
			if ($currentDateAsString !== $newDateAsString) {
				$this->created_at = $newDateAsString;
				$this->modifiedColumns[] = TblVoiturePeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [deleted_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.
	 *               Empty strings are treated as NULL.
	 * @return     TblVoiture The current object (for fluent API support)
	 */
	public function setDeletedAt($v)
	{
		$dt = PropelDateTime::newInstance($v, null, 'DateTime');
		if ($this->deleted_at !== null || $dt !== null) {
			$currentDateAsString = ($this->deleted_at !== null && $tmpDt = new DateTime($this->deleted_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newDateAsString = $dt ? $dt->format('Y-m-d H:i:s') : null;
			if ($currentDateAsString !== $newDateAsString) {
				$this->deleted_at = $newDateAsString;
				$this->modifiedColumns[] = TblVoiturePeer::DELETED_AT;
			}
		} // if either are not null

		return $this;
	} // setDeletedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id_voiture = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->id_client = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->immatriculation = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->id_marque = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->id_motorisation = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->couleur = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->nbr_portes = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->modele = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->annee = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
			$this->nb_visite = ($row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->created_at = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->deleted_at = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			return $startcol + 12; // 12 = TblVoiturePeer::NUM_HYDRATE_COLUMNS.

		} catch (Exception $e) {
			throw new PropelException("Error populating TblVoiture object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aTblClient !== null && $this->id_client !== $this->aTblClient->getIdClient()) {
			$this->aTblClient = null;
		}
		if ($this->aRefMarque !== null && $this->id_marque !== $this->aRefMarque->getMarqueId()) {
			$this->aRefMarque = null;
		}
		if ($this->aRefMotorisation !== null && $this->id_motorisation !== $this->aRefMotorisation->getIdMotorisation()) {
			$this->aRefMotorisation = null;
		}
		if ($this->aRefNbrPortes !== null && $this->nbr_portes !== $this->aRefNbrPortes->getIdNbrPortes()) {
			$this->aRefNbrPortes = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TblVoiturePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = TblVoiturePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aTblClient = null;
			$this->aRefMarque = null;
			$this->aRefMotorisation = null;
			$this->aRefNbrPortes = null;
			$this->collTblFactures = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TblVoiturePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$con->beginTransaction();
		try {
			$deleteQuery = TblVoitureQuery::create()
				->filterByPrimaryKey($this->getPrimaryKey());
			$ret = $this->preDelete($con);
			// soft_delete behavior
			if (!empty($ret) && TblVoitureQuery::isSoftDeleteEnabled()) {
				$this->setDeletedAt(time());
				$this->save($con);
				$this->postDelete($con);
				$con->commit();
				TblVoiturePeer::removeInstanceFromPool($this);
				return;
			}

			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseTblVoiture:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			    return;
			  }
			}

			if ($ret) {
				$deleteQuery->delete($con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseTblVoiture:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$con->commit();
				$this->setDeleted(true);
			} else {
				$con->commit();
			}
		} catch (Exception $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TblVoiturePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseTblVoiture:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			  	$con->commit();
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(TblVoiturePeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseTblVoiture:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				TblVoiturePeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (Exception $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aTblClient !== null) {
				if ($this->aTblClient->isModified() || $this->aTblClient->isNew()) {
					$affectedRows += $this->aTblClient->save($con);
				}
				$this->setTblClient($this->aTblClient);
			}

			if ($this->aRefMarque !== null) {
				if ($this->aRefMarque->isModified() || $this->aRefMarque->isNew()) {
					$affectedRows += $this->aRefMarque->save($con);
				}
				$this->setRefMarque($this->aRefMarque);
			}

			if ($this->aRefMotorisation !== null) {
				if ($this->aRefMotorisation->isModified() || $this->aRefMotorisation->isNew()) {
					$affectedRows += $this->aRefMotorisation->save($con);
				}
				$this->setRefMotorisation($this->aRefMotorisation);
			}

			if ($this->aRefNbrPortes !== null) {
				if ($this->aRefNbrPortes->isModified() || $this->aRefNbrPortes->isNew()) {
					$affectedRows += $this->aRefNbrPortes->save($con);
				}
				$this->setRefNbrPortes($this->aRefNbrPortes);
			}

			if ($this->isNew() || $this->isModified()) {
				// persist changes
				if ($this->isNew()) {
					$this->doInsert($con);
				} else {
					$this->doUpdate($con);
				}
				$affectedRows += 1;
				$this->resetModified();
			}

			if ($this->tblFacturesScheduledForDeletion !== null) {
				if (!$this->tblFacturesScheduledForDeletion->isEmpty()) {
					TblFactureQuery::create()
						->filterByPrimaryKeys($this->tblFacturesScheduledForDeletion->getPrimaryKeys(false))
						->delete($con);
					$this->tblFacturesScheduledForDeletion = null;
				}
			}

			if ($this->collTblFactures !== null) {
				foreach ($this->collTblFactures as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Insert the row in the database.
	 *
	 * @param      PropelPDO $con
	 *
	 * @throws     PropelException
	 * @see        doSave()
	 */
	protected function doInsert(PropelPDO $con)
	{
		$modifiedColumns = array();
		$index = 0;

		$this->modifiedColumns[] = TblVoiturePeer::ID_VOITURE;
		if (null !== $this->id_voiture) {
			throw new PropelException('Cannot insert a value for auto-increment primary key (' . TblVoiturePeer::ID_VOITURE . ')');
		}

		 // check the columns in natural order for more readable SQL queries
		if ($this->isColumnModified(TblVoiturePeer::ID_VOITURE)) {
			$modifiedColumns[':p' . $index++]  = '`ID_VOITURE`';
		}
		if ($this->isColumnModified(TblVoiturePeer::ID_CLIENT)) {
			$modifiedColumns[':p' . $index++]  = '`ID_CLIENT`';
		}
		if ($this->isColumnModified(TblVoiturePeer::IMMATRICULATION)) {
			$modifiedColumns[':p' . $index++]  = '`IMMATRICULATION`';
		}
		if ($this->isColumnModified(TblVoiturePeer::ID_MARQUE)) {
			$modifiedColumns[':p' . $index++]  = '`ID_MARQUE`';
		}
		if ($this->isColumnModified(TblVoiturePeer::ID_MOTORISATION)) {
			$modifiedColumns[':p' . $index++]  = '`ID_MOTORISATION`';
		}
		if ($this->isColumnModified(TblVoiturePeer::COULEUR)) {
			$modifiedColumns[':p' . $index++]  = '`COULEUR`';
		}
		if ($this->isColumnModified(TblVoiturePeer::NBR_PORTES)) {
			$modifiedColumns[':p' . $index++]  = '`NBR_PORTES`';
		}
		if ($this->isColumnModified(TblVoiturePeer::MODELE)) {
			$modifiedColumns[':p' . $index++]  = '`MODELE`';
		}
		if ($this->isColumnModified(TblVoiturePeer::ANNEE)) {
			$modifiedColumns[':p' . $index++]  = '`ANNEE`';
		}
		if ($this->isColumnModified(TblVoiturePeer::NB_VISITE)) {
			$modifiedColumns[':p' . $index++]  = '`NB_VISITE`';
		}
		if ($this->isColumnModified(TblVoiturePeer::CREATED_AT)) {
			$modifiedColumns[':p' . $index++]  = '`CREATED_AT`';
		}
		if ($this->isColumnModified(TblVoiturePeer::DELETED_AT)) {
			$modifiedColumns[':p' . $index++]  = '`DELETED_AT`';
		}

		$sql = sprintf(
			'INSERT INTO `tbl_voiture` (%s) VALUES (%s)',
			implode(', ', $modifiedColumns),
			implode(', ', array_keys($modifiedColumns))
		);

		try {
			$stmt = $con->prepare($sql);
			foreach ($modifiedColumns as $identifier => $columnName) {
				switch ($columnName) {
					case '`ID_VOITURE`':
						$stmt->bindValue($identifier, $this->id_voiture, PDO::PARAM_INT);
						break;
					case '`ID_CLIENT`':
						$stmt->bindValue($identifier, $this->id_client, PDO::PARAM_INT);
						break;
					case '`IMMATRICULATION`':
						$stmt->bindValue($identifier, $this->immatriculation, PDO::PARAM_STR);
						break;
					case '`ID_MARQUE`':
						$stmt->bindValue($identifier, $this->id_marque, PDO::PARAM_INT);
						break;
					case '`ID_MOTORISATION`':
						$stmt->bindValue($identifier, $this->id_motorisation, PDO::PARAM_INT);
						break;
					case '`COULEUR`':
						$stmt->bindValue($identifier, $this->couleur, PDO::PARAM_STR);
						break;
					case '`NBR_PORTES`':
						$stmt->bindValue($identifier, $this->nbr_portes, PDO::PARAM_INT);
						break;
					case '`MODELE`':
						$stmt->bindValue($identifier, $this->modele, PDO::PARAM_STR);
						break;
					case '`ANNEE`':
						$stmt->bindValue($identifier, $this->annee, PDO::PARAM_INT);
						break;
					case '`NB_VISITE`':
						$stmt->bindValue($identifier, $this->nb_visite, PDO::PARAM_INT);
						break;
					case '`CREATED_AT`':
						$stmt->bindValue($identifier, $this->created_at, PDO::PARAM_STR);
						break;
					case '`DELETED_AT`':
						$stmt->bindValue($identifier, $this->deleted_at, PDO::PARAM_STR);
						break;
				}
			}
			$stmt->execute();
		} catch (Exception $e) {
			Propel::log($e->getMessage(), Propel::LOG_ERR);
			throw new PropelException(sprintf('Unable to execute INSERT statement [%s]', $sql), $e);
		}

		try {
			$pk = $con->lastInsertId();
		} catch (Exception $e) {
			throw new PropelException('Unable to get autoincrement id.', $e);
		}
		$this->setIdVoiture($pk);

		$this->setNew(false);
	}

	/**
	 * Update the row in the database.
	 *
	 * @param      PropelPDO $con
	 *
	 * @see        doSave()
	 */
	protected function doUpdate(PropelPDO $con)
	{
		$selectCriteria = $this->buildPkeyCriteria();
		$valuesCriteria = $this->buildCriteria();
		BasePeer::doUpdate($selectCriteria, $valuesCriteria, $con);
	}

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aTblClient !== null) {
				if (!$this->aTblClient->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTblClient->getValidationFailures());
				}
			}

			if ($this->aRefMarque !== null) {
				if (!$this->aRefMarque->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aRefMarque->getValidationFailures());
				}
			}

			if ($this->aRefMotorisation !== null) {
				if (!$this->aRefMotorisation->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aRefMotorisation->getValidationFailures());
				}
			}

			if ($this->aRefNbrPortes !== null) {
				if (!$this->aRefNbrPortes->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aRefNbrPortes->getValidationFailures());
				}
			}


			if (($retval = TblVoiturePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collTblFactures !== null) {
					foreach ($this->collTblFactures as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = TblVoiturePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getIdVoiture();
				break;
			case 1:
				return $this->getIdClient();
				break;
			case 2:
				return $this->getImmatriculation();
				break;
			case 3:
				return $this->getIdMarque();
				break;
			case 4:
				return $this->getIdMotorisation();
				break;
			case 5:
				return $this->getCouleur();
				break;
			case 6:
				return $this->getNbrPortes();
				break;
			case 7:
				return $this->getModele();
				break;
			case 8:
				return $this->getAnnee();
				break;
			case 9:
				return $this->getNbVisite();
				break;
			case 10:
				return $this->getCreatedAt();
				break;
			case 11:
				return $this->getDeletedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param     string  $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 *                    BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 *                    Defaults to BasePeer::TYPE_PHPNAME.
	 * @param     boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns. Defaults to TRUE.
	 * @param     array $alreadyDumpedObjects List of objects to skip to avoid recursion
	 * @param     boolean $includeForeignObjects (optional) Whether to include hydrated related objects. Default to FALSE.
	 *
	 * @return    array an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true, $alreadyDumpedObjects = array(), $includeForeignObjects = false)
	{
		if (isset($alreadyDumpedObjects['TblVoiture'][$this->getPrimaryKey()])) {
			return '*RECURSION*';
		}
		$alreadyDumpedObjects['TblVoiture'][$this->getPrimaryKey()] = true;
		$keys = TblVoiturePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getIdVoiture(),
			$keys[1] => $this->getIdClient(),
			$keys[2] => $this->getImmatriculation(),
			$keys[3] => $this->getIdMarque(),
			$keys[4] => $this->getIdMotorisation(),
			$keys[5] => $this->getCouleur(),
			$keys[6] => $this->getNbrPortes(),
			$keys[7] => $this->getModele(),
			$keys[8] => $this->getAnnee(),
			$keys[9] => $this->getNbVisite(),
			$keys[10] => $this->getCreatedAt(),
			$keys[11] => $this->getDeletedAt(),
		);
		if ($includeForeignObjects) {
			if (null !== $this->aTblClient) {
				$result['TblClient'] = $this->aTblClient->toArray($keyType, $includeLazyLoadColumns,  $alreadyDumpedObjects, true);
			}
			if (null !== $this->aRefMarque) {
				$result['RefMarque'] = $this->aRefMarque->toArray($keyType, $includeLazyLoadColumns,  $alreadyDumpedObjects, true);
			}
			if (null !== $this->aRefMotorisation) {
				$result['RefMotorisation'] = $this->aRefMotorisation->toArray($keyType, $includeLazyLoadColumns,  $alreadyDumpedObjects, true);
			}
			if (null !== $this->aRefNbrPortes) {
				$result['RefNbrPortes'] = $this->aRefNbrPortes->toArray($keyType, $includeLazyLoadColumns,  $alreadyDumpedObjects, true);
			}
			if (null !== $this->collTblFactures) {
				$result['TblFactures'] = $this->collTblFactures->toArray(null, true, $keyType, $includeLazyLoadColumns, $alreadyDumpedObjects);
			}
		}
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = TblVoiturePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setIdVoiture($value);
				break;
			case 1:
				$this->setIdClient($value);
				break;
			case 2:
				$this->setImmatriculation($value);
				break;
			case 3:
				$this->setIdMarque($value);
				break;
			case 4:
				$this->setIdMotorisation($value);
				break;
			case 5:
				$this->setCouleur($value);
				break;
			case 6:
				$this->setNbrPortes($value);
				break;
			case 7:
				$this->setModele($value);
				break;
			case 8:
				$this->setAnnee($value);
				break;
			case 9:
				$this->setNbVisite($value);
				break;
			case 10:
				$this->setCreatedAt($value);
				break;
			case 11:
				$this->setDeletedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = TblVoiturePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setIdVoiture($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setIdClient($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setImmatriculation($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setIdMarque($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setIdMotorisation($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setCouleur($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setNbrPortes($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setModele($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setAnnee($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setNbVisite($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setCreatedAt($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setDeletedAt($arr[$keys[11]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(TblVoiturePeer::DATABASE_NAME);

		if ($this->isColumnModified(TblVoiturePeer::ID_VOITURE)) $criteria->add(TblVoiturePeer::ID_VOITURE, $this->id_voiture);
		if ($this->isColumnModified(TblVoiturePeer::ID_CLIENT)) $criteria->add(TblVoiturePeer::ID_CLIENT, $this->id_client);
		if ($this->isColumnModified(TblVoiturePeer::IMMATRICULATION)) $criteria->add(TblVoiturePeer::IMMATRICULATION, $this->immatriculation);
		if ($this->isColumnModified(TblVoiturePeer::ID_MARQUE)) $criteria->add(TblVoiturePeer::ID_MARQUE, $this->id_marque);
		if ($this->isColumnModified(TblVoiturePeer::ID_MOTORISATION)) $criteria->add(TblVoiturePeer::ID_MOTORISATION, $this->id_motorisation);
		if ($this->isColumnModified(TblVoiturePeer::COULEUR)) $criteria->add(TblVoiturePeer::COULEUR, $this->couleur);
		if ($this->isColumnModified(TblVoiturePeer::NBR_PORTES)) $criteria->add(TblVoiturePeer::NBR_PORTES, $this->nbr_portes);
		if ($this->isColumnModified(TblVoiturePeer::MODELE)) $criteria->add(TblVoiturePeer::MODELE, $this->modele);
		if ($this->isColumnModified(TblVoiturePeer::ANNEE)) $criteria->add(TblVoiturePeer::ANNEE, $this->annee);
		if ($this->isColumnModified(TblVoiturePeer::NB_VISITE)) $criteria->add(TblVoiturePeer::NB_VISITE, $this->nb_visite);
		if ($this->isColumnModified(TblVoiturePeer::CREATED_AT)) $criteria->add(TblVoiturePeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(TblVoiturePeer::DELETED_AT)) $criteria->add(TblVoiturePeer::DELETED_AT, $this->deleted_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(TblVoiturePeer::DATABASE_NAME);
		$criteria->add(TblVoiturePeer::ID_VOITURE, $this->id_voiture);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getIdVoiture();
	}

	/**
	 * Generic method to set the primary key (id_voiture column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setIdVoiture($key);
	}

	/**
	 * Returns true if the primary key for this object is null.
	 * @return     boolean
	 */
	public function isPrimaryKeyNull()
	{
		return null === $this->getIdVoiture();
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of TblVoiture (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @param      boolean $makeNew Whether to reset autoincrement PKs and make the object new.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false, $makeNew = true)
	{
		$copyObj->setIdClient($this->getIdClient());
		$copyObj->setImmatriculation($this->getImmatriculation());
		$copyObj->setIdMarque($this->getIdMarque());
		$copyObj->setIdMotorisation($this->getIdMotorisation());
		$copyObj->setCouleur($this->getCouleur());
		$copyObj->setNbrPortes($this->getNbrPortes());
		$copyObj->setModele($this->getModele());
		$copyObj->setAnnee($this->getAnnee());
		$copyObj->setNbVisite($this->getNbVisite());
		$copyObj->setCreatedAt($this->getCreatedAt());
		$copyObj->setDeletedAt($this->getDeletedAt());

		if ($deepCopy && !$this->startCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);
			// store object hash to prevent cycle
			$this->startCopy = true;

			foreach ($this->getTblFactures() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addTblFacture($relObj->copy($deepCopy));
				}
			}

			//unflag object copy
			$this->startCopy = false;
		} // if ($deepCopy)

		if ($makeNew) {
			$copyObj->setNew(true);
			$copyObj->setIdVoiture(NULL); // this is a auto-increment column, so set to default value
		}
	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     TblVoiture Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     TblVoiturePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new TblVoiturePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a TblClient object.
	 *
	 * @param      TblClient $v
	 * @return     TblVoiture The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTblClient(TblClient $v = null)
	{
		if ($v === null) {
			$this->setIdClient(NULL);
		} else {
			$this->setIdClient($v->getIdClient());
		}

		$this->aTblClient = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the TblClient object, it will not be re-added.
		if ($v !== null) {
			$v->addTblVoiture($this);
		}

		return $this;
	}


	/**
	 * Get the associated TblClient object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     TblClient The associated TblClient object.
	 * @throws     PropelException
	 */
	public function getTblClient(PropelPDO $con = null)
	{
		if ($this->aTblClient === null && ($this->id_client !== null)) {
			$this->aTblClient = TblClientQuery::create()->findPk($this->id_client, $con);
			/* The following can be used additionally to
				guarantee the related object contains a reference
				to this object.  This level of coupling may, however, be
				undesirable since it could result in an only partially populated collection
				in the referenced object.
				$this->aTblClient->addTblVoitures($this);
			 */
		}
		return $this->aTblClient;
	}

	/**
	 * Declares an association between this object and a RefMarque object.
	 *
	 * @param      RefMarque $v
	 * @return     TblVoiture The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setRefMarque(RefMarque $v = null)
	{
		if ($v === null) {
			$this->setIdMarque(NULL);
		} else {
			$this->setIdMarque($v->getMarqueId());
		}

		$this->aRefMarque = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the RefMarque object, it will not be re-added.
		if ($v !== null) {
			$v->addTblVoiture($this);
		}

		return $this;
	}


	/**
	 * Get the associated RefMarque object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     RefMarque The associated RefMarque object.
	 * @throws     PropelException
	 */
	public function getRefMarque(PropelPDO $con = null)
	{
		if ($this->aRefMarque === null && ($this->id_marque !== null)) {
			$this->aRefMarque = RefMarqueQuery::create()->findPk($this->id_marque, $con);
			/* The following can be used additionally to
				guarantee the related object contains a reference
				to this object.  This level of coupling may, however, be
				undesirable since it could result in an only partially populated collection
				in the referenced object.
				$this->aRefMarque->addTblVoitures($this);
			 */
		}
		return $this->aRefMarque;
	}

	/**
	 * Declares an association between this object and a RefMotorisation object.
	 *
	 * @param      RefMotorisation $v
	 * @return     TblVoiture The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setRefMotorisation(RefMotorisation $v = null)
	{
		if ($v === null) {
			$this->setIdMotorisation(NULL);
		} else {
			$this->setIdMotorisation($v->getIdMotorisation());
		}

		$this->aRefMotorisation = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the RefMotorisation object, it will not be re-added.
		if ($v !== null) {
			$v->addTblVoiture($this);
		}

		return $this;
	}


	/**
	 * Get the associated RefMotorisation object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     RefMotorisation The associated RefMotorisation object.
	 * @throws     PropelException
	 */
	public function getRefMotorisation(PropelPDO $con = null)
	{
		if ($this->aRefMotorisation === null && ($this->id_motorisation !== null)) {
			$this->aRefMotorisation = RefMotorisationQuery::create()->findPk($this->id_motorisation, $con);
			/* The following can be used additionally to
				guarantee the related object contains a reference
				to this object.  This level of coupling may, however, be
				undesirable since it could result in an only partially populated collection
				in the referenced object.
				$this->aRefMotorisation->addTblVoitures($this);
			 */
		}
		return $this->aRefMotorisation;
	}

	/**
	 * Declares an association between this object and a RefNbrPortes object.
	 *
	 * @param      RefNbrPortes $v
	 * @return     TblVoiture The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setRefNbrPortes(RefNbrPortes $v = null)
	{
		if ($v === null) {
			$this->setNbrPortes(NULL);
		} else {
			$this->setNbrPortes($v->getIdNbrPortes());
		}

		$this->aRefNbrPortes = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the RefNbrPortes object, it will not be re-added.
		if ($v !== null) {
			$v->addTblVoiture($this);
		}

		return $this;
	}


	/**
	 * Get the associated RefNbrPortes object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     RefNbrPortes The associated RefNbrPortes object.
	 * @throws     PropelException
	 */
	public function getRefNbrPortes(PropelPDO $con = null)
	{
		if ($this->aRefNbrPortes === null && ($this->nbr_portes !== null)) {
			$this->aRefNbrPortes = RefNbrPortesQuery::create()->findPk($this->nbr_portes, $con);
			/* The following can be used additionally to
				guarantee the related object contains a reference
				to this object.  This level of coupling may, however, be
				undesirable since it could result in an only partially populated collection
				in the referenced object.
				$this->aRefNbrPortes->addTblVoitures($this);
			 */
		}
		return $this->aRefNbrPortes;
	}


	/**
	 * Initializes a collection based on the name of a relation.
	 * Avoids crafting an 'init[$relationName]s' method name
	 * that wouldn't work when StandardEnglishPluralizer is used.
	 *
	 * @param      string $relationName The name of the relation to initialize
	 * @return     void
	 */
	public function initRelation($relationName)
	{
		if ('TblFacture' == $relationName) {
			return $this->initTblFactures();
		}
	}

	/**
	 * Clears out the collTblFactures collection
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addTblFactures()
	 */
	public function clearTblFactures()
	{
		$this->collTblFactures = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collTblFactures collection.
	 *
	 * By default this just sets the collTblFactures collection to an empty array (like clearcollTblFactures());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @param      boolean $overrideExisting If set to true, the method call initializes
	 *                                        the collection even if it is not empty
	 *
	 * @return     void
	 */
	public function initTblFactures($overrideExisting = true)
	{
		if (null !== $this->collTblFactures && !$overrideExisting) {
			return;
		}
		$this->collTblFactures = new PropelObjectCollection();
		$this->collTblFactures->setModel('TblFacture');
	}

	/**
	 * Gets an array of TblFacture objects which contain a foreign key that references this object.
	 *
	 * If the $criteria is not null, it is used to always fetch the results from the database.
	 * Otherwise the results are fetched from the database the first time, then cached.
	 * Next time the same method is called without $criteria, the cached collection is returned.
	 * If this TblVoiture is new, it will return
	 * an empty collection or the current collection; the criteria is ignored on a new object.
	 *
	 * @param      Criteria $criteria optional Criteria object to narrow the query
	 * @param      PropelPDO $con optional connection object
	 * @return     PropelCollection|array TblFacture[] List of TblFacture objects
	 * @throws     PropelException
	 */
	public function getTblFactures($criteria = null, PropelPDO $con = null)
	{
		if(null === $this->collTblFactures || null !== $criteria) {
			if ($this->isNew() && null === $this->collTblFactures) {
				// return empty collection
				$this->initTblFactures();
			} else {
				$collTblFactures = TblFactureQuery::create(null, $criteria)
					->filterByTblVoiture($this)
					->find($con);
				if (null !== $criteria) {
					return $collTblFactures;
				}
				$this->collTblFactures = $collTblFactures;
			}
		}
		return $this->collTblFactures;
	}

	/**
	 * Sets a collection of TblFacture objects related by a one-to-many relationship
	 * to the current object.
	 * It will also schedule objects for deletion based on a diff between old objects (aka persisted)
	 * and new objects from the given Propel collection.
	 *
	 * @param      PropelCollection $tblFactures A Propel collection.
	 * @param      PropelPDO $con Optional connection object
	 */
	public function setTblFactures(PropelCollection $tblFactures, PropelPDO $con = null)
	{
		$this->tblFacturesScheduledForDeletion = $this->getTblFactures(new Criteria(), $con)->diff($tblFactures);

		foreach ($tblFactures as $tblFacture) {
			// Fix issue with collection modified by reference
			if ($tblFacture->isNew()) {
				$tblFacture->setTblVoiture($this);
			}
			$this->addTblFacture($tblFacture);
		}

		$this->collTblFactures = $tblFactures;
	}

	/**
	 * Returns the number of related TblFacture objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related TblFacture objects.
	 * @throws     PropelException
	 */
	public function countTblFactures(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if(null === $this->collTblFactures || null !== $criteria) {
			if ($this->isNew() && null === $this->collTblFactures) {
				return 0;
			} else {
				$query = TblFactureQuery::create(null, $criteria);
				if($distinct) {
					$query->distinct();
				}
				return $query
					->filterByTblVoiture($this)
					->count($con);
			}
		} else {
			return count($this->collTblFactures);
		}
	}

	/**
	 * Method called to associate a TblFacture object to this object
	 * through the TblFacture foreign key attribute.
	 *
	 * @param      TblFacture $l TblFacture
	 * @return     TblVoiture The current object (for fluent API support)
	 */
	public function addTblFacture(TblFacture $l)
	{
		if ($this->collTblFactures === null) {
			$this->initTblFactures();
		}
		if (!$this->collTblFactures->contains($l)) { // only add it if the **same** object is not already associated
			$this->doAddTblFacture($l);
		}

		return $this;
	}

	/**
	 * @param	TblFacture $tblFacture The tblFacture object to add.
	 */
	protected function doAddTblFacture($tblFacture)
	{
		$this->collTblFactures[]= $tblFacture;
		$tblFacture->setTblVoiture($this);
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this TblVoiture is new, it will return
	 * an empty collection; or if this TblVoiture has previously
	 * been saved, it will retrieve related TblFactures from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in TblVoiture.
	 *
	 * @param      Criteria $criteria optional Criteria object to narrow the query
	 * @param      PropelPDO $con optional connection object
	 * @param      string $join_behavior optional join type to use (defaults to Criteria::LEFT_JOIN)
	 * @return     PropelCollection|array TblFacture[] List of TblFacture objects
	 */
	public function getTblFacturesJoinTblClient($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$query = TblFactureQuery::create(null, $criteria);
		$query->joinWith('TblClient', $join_behavior);

		return $this->getTblFactures($query, $con);
	}

	/**
	 * Clears the current object and sets all attributes to their default values
	 */
	public function clear()
	{
		$this->id_voiture = null;
		$this->id_client = null;
		$this->immatriculation = null;
		$this->id_marque = null;
		$this->id_motorisation = null;
		$this->couleur = null;
		$this->nbr_portes = null;
		$this->modele = null;
		$this->annee = null;
		$this->nb_visite = null;
		$this->created_at = null;
		$this->deleted_at = null;
		$this->alreadyInSave = false;
		$this->alreadyInValidation = false;
		$this->clearAllReferences();
		$this->resetModified();
		$this->setNew(true);
		$this->setDeleted(false);
	}

	/**
	 * Resets all references to other model objects or collections of model objects.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect
	 * objects with circular references (even in PHP 5.3). This is currently necessary
	 * when using Propel in certain daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all referrer objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collTblFactures) {
				foreach ($this->collTblFactures as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		if ($this->collTblFactures instanceof PropelCollection) {
			$this->collTblFactures->clearIterator();
		}
		$this->collTblFactures = null;
		$this->aTblClient = null;
		$this->aRefMarque = null;
		$this->aRefMotorisation = null;
		$this->aRefNbrPortes = null;
	}

	/**
	 * Return the string representation of this object
	 *
	 * @return string
	 */
	public function __toString()
	{
		return (string) $this->exportTo(TblVoiturePeer::DEFAULT_STRING_FORMAT);
	}

	// soft_delete behavior
	
	/**
	 * Bypass the soft_delete behavior and force a hard delete of the current object
	 */
	public function forceDelete(PropelPDO $con = null)
	{
		if($isSoftDeleteEnabled = TblVoiturePeer::isSoftDeleteEnabled()) {
			TblVoiturePeer::disableSoftDelete();
		}
		$this->delete($con);
		if ($isSoftDeleteEnabled) {
			TblVoiturePeer::enableSoftDelete();
		}
	}
	
	/**
	 * Undelete a row that was soft_deleted
	 *
	 * @return		 int The number of rows affected by this update and any referring fk objects' save() operations.
	 */
	public function unDelete(PropelPDO $con = null)
	{
		$this->setDeletedAt(null);
		return $this->save($con);
	}

	/**
	 * Catches calls to virtual methods
	 */
	public function __call($name, $params)
	{
		
		// symfony_behaviors behavior
		if ($callable = sfMixer::getCallable('BaseTblVoiture:' . $name))
		{
		  array_unshift($params, $this);
		  return call_user_func_array($callable, $params);
		}

		return parent::__call($name, $params);
	}

} // BaseTblVoiture
