<?php



/**
 * Skeleton subclass for performing query and update operations on the 'ref_nbr_portes' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.6-dev on:
 *
 * 11/14/13 14:53:06
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class RefNbrPortesPeer extends BaseRefNbrPortesPeer {

} // RefNbrPortesPeer
