<?php



/**
 * Skeleton subclass for performing query and update operations on the 'tbl_client' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.6-dev on:
 *
 * 10/12/13 18:14:04
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class TblClientQuery extends BaseTblClientQuery {

    public function filterByDatatable($searchs = "") {
        if ($searchs == '')
            return $this;
        $arrayCondition = $arrayCombine = array();
        foreach (explode(" ", $searchs) as $i => $search) {
            $search = '%' . $search . '%';

            $this->condition('nomClient' . $i, 'TblClient.NomClient LIKE ?', $search)
                    ->condition('prenomClient' . $i, 'TblClient.PrenomClient LIKE ?', $search)
                    ->condition('ageClient' . $i, 'TblClient.AgeClient LIKE ?', $search)
                    ->condition('NumTel' . $i, 'TblClient.NumTel LIKE ?', $search);

            $arrayCondition[] = 'nomClient' . $i;
            $arrayCondition[] = 'prenomClient' . $i;
            $arrayCondition[] = 'ageClient' . $i;
            $arrayCondition[] = 'NumTel' . $i;

            $this->combine($arrayCondition, 'or', "combine" . $i);
            $arrayCombine[] = "combine" . $i;
            $arrayCondition = array();
        }

        return $this->combine($arrayCombine, 'and');
    }

    public function orderByDatatable($col, $order) {
        switch ($col) {
            case 0:
                $this->orderByNomClient($order);
                break;
            case 1:
                $this->orderByPrenomClient($order);
                break;
        }
        return $this;
    }
} // TblClientQuery
