<?php

/**
 * Skeleton subclass for representing a row from the 'tbl_objectif' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.6-dev on:
 *
 * 10/19/13 10:41:32
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class TblObjectif extends BaseTblObjectif {

    public function getObjectifFixe1() {

        return 11;
    }

    public function getObjectifFixByDate($mois) {
        $annee = date('Y');
        $jourCourant = 'DAY(' . TblObjectifPeer::OBJECTIF_DATE . ')between 1 and 31';
        $moisCourant = 'MONTH(' . TblObjectifPeer::OBJECTIF_DATE . ')=' . $mois;
        $anneeCourante = 'YEAR(' . TblObjectifPeer::OBJECTIF_DATE . ')=' . $annee;
        $ObjectifFixe = TblObjectifQuery::create()
                ->addAnd(TblObjectifPeer::OBJECTIF_DATE, $jourCourant, Criteria::CUSTOM)
                ->addAnd(TblObjectifPeer::OBJECTIF_DATE, $moisCourant, Criteria::CUSTOM)
                ->addAnd(TblObjectifPeer::OBJECTIF_DATE, $anneeCourante, Criteria::CUSTOM)
                ->withColumn('SUM(' . TblObjectifPeer::OBJECTIF_FIXE . ')', "totalFix")
                ->select('totalFix')
                ->findOne();
        if ($ObjectifFixe) {
            return $ObjectifFixe;
        } else {
            return 00;
        }
        echo Propel::getConnection()->getLastExecutedQuery();
        die;
    }

    public function getObjectifRealiseByDate($mois) {
        $annee = date('Y');
        $jourCourant = 'DAY(' . TblObjectifPeer::OBJECTIF_DATE . ')between 1 and 31';
        $moisCourant = 'MONTH(' . TblObjectifPeer::OBJECTIF_DATE . ')=' . $mois;
        $anneeCourante = 'YEAR(' . TblObjectifPeer::OBJECTIF_DATE . ')=' . $annee;
        $ObjectifRealise = TblObjectifQuery::create()
                ->addAnd(TblObjectifPeer::OBJECTIF_DATE, $jourCourant, Criteria::CUSTOM)
                ->addAnd(TblObjectifPeer::OBJECTIF_DATE, $moisCourant, Criteria::CUSTOM)
                ->addAnd(TblObjectifPeer::OBJECTIF_DATE, $anneeCourante, Criteria::CUSTOM)
                ->withColumn('SUM(' . TblObjectifPeer::OBJECTIF_REALISE . ')', "totalRealise")
                ->select('totalRealise')
                ->findOne();
        if ($ObjectifRealise) {
            return $ObjectifRealise;
        } else {
            return 00;
        }
        echo Propel::getConnection()->getLastExecutedQuery();
        die;
    }

    function get_month_name($month) {
        $months = array(
            '01' => 'Janvier',
            '02' => 'Février',
            '03' => 'Mars',
            '04' => 'Avril',
            '05' => 'Mai',
            '06' => 'Juin',
            '07' => 'Juillet',
            '08' => 'Aôut',
            '09' => 'September',
            '10' => 'October',
            '11' => 'November',
            '12' => 'December'
        );
        return $months[$month];
    }

}

// TblObjectif
