<?php



/**
 * Skeleton subclass for performing query and update operations on the 'tbl_tapis' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.6-dev on:
 *
 * 11/27/13 15:56:17
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class TblTapisPeer extends BaseTblTapisPeer {

} // TblTapisPeer
