<?php



/**
 * Skeleton subclass for performing query and update operations on the 'tbl_tapis' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.6-dev on:
 *
 * 11/27/13 15:56:17
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class TblTapisQuery extends BaseTblTapisQuery {

    public function filterByDatatable($searchs = "") {
        if ($searchs == '')
            return $this;
        $arrayCondition = $arrayCombine = array();
        foreach (explode(" ", $searchs) as $i => $search) {
            $search = '%' . $search . '%';

            $this->condition('NumTapis' . $i, 'TblTapis.NumTapis LIKE ?', $search)
                    ->condition('TailleTapis' . $i, 'TblTapis.TailleTapis LIKE ?', $search)
                    ->condition('PrixMettreCarre' . $i, 'TblTapis.PrixMettreCarre LIKE ?', $search)
                    ->condition('MontantLavageTapis' . $i, 'TblTapis.MontantLavageTapis LIKE ?', $search);

            $arrayCondition[] = 'NumTapis' . $i;
            $arrayCondition[] = 'TailleTapis' . $i;
            $arrayCondition[] = 'PrixMettreCarre' . $i;
            $arrayCondition[] = 'MontantLavageTapis' . $i;

            $this->combine($arrayCondition, 'or', "combine" . $i);
            $arrayCombine[] = "combine" . $i;
            $arrayCondition = array();
        }

        return $this->combine($arrayCombine, 'and');
    }

    public function orderByDatatable($col, $order) {
        switch ($col) {
//            case 0:
//                $this->orderByNomClient($order);
//                break;
//            case 1:
//                $this->orderByPrenomClient($order);
//                break;
        }
        return $this;
    }
    
} // TblTapisQuery
