<?php

/**
 * Skeleton subclass for performing query and update operations on the 'tbl_voiture' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.6-dev on:
 *
 * 10/12/13 18:14:04
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class TblVoiturePeer extends BaseTblVoiturePeer {

    static public function retrieveForSelect($q, $limit) {
        $criteria = new Criteria();
        $criteria->add(TblVoiturePeer::IMMATRICULATION, '%' . $q . '%', Criteria::LIKE);
        $criteria->addAscendingOrderByColumn(TblVoiturePeer::IMMATRICULATION);
        $criteria->setLimit($limit);

        $authors = array();
        foreach (TblVoiturePeer::doSelect($criteria) as $author) {
            $authors[$author->getIdVoiture()] = (string) $author;
        }

        return $authors;
    }

}

// TblVoiturePeer
